print ("Hello World!")
print ("Hello Again.")
print ("I like typing this")
print ("This is fun")
print ('Yay! Printing.')
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.\n')
print ('Printing on a\nnew line')
# print ('this will not print')